CREATE TABLE IF NOT EXISTS currency (
    id CHARACTER VARYING(7) NOT NULL PRIMARY KEY,
    "NumCode" INT NOT NULL,
    "CharCode" CHARACTER VARYING(9) NOT NULL,
    "Nominal" INT NOT NULL,
    "Name" CHARACTER VARYING(50) NOT NULL,
    "Value" REAL NOT NULL,
    "Previous" REAL NOT NULL
);
