version: '3.9'
services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - /app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ../postgres/pg:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

