version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'currency'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
