version: '3.9'
services:
   postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./postgres/pg:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

   main:
     container_name: main
     build:
       context: .
     env_file:
       - .env
     ports:
       - '127.0.0.1:8080:8080'
     depends_on:
       - postgres
     command: sh -c 'wait && npx sequelize-cli db:migrate && npm run start:dev'
     restart: always